### PR TITLE
Enable Capture of Multiple Fingerprints

### PR DESCRIPTION
**Pull request by slubwama**
https://trello.com/c/fVSxDyb0/744-enable-capturing-of-multiple-fingerprint

### CODE REVIEW

**Comment by ssmusoke** [comment]
@slubwama does this also make the module compatible with OpenMRS 2.x?

**Comment by slubwama** [comment]
@ssmusoke the module is already compatible with  2.x

**Comment by ssmusoke** [comment]
@slubwama I noticed it compiles with Java 7 and requires platform 1.11.x can you up those to 2.x and Java 8 so that we don't run into compatibility issues as we keep upgrading

**Comment by slubwama** [comment]
Will do that in a separate PR that may be defined for miscellaneous.  Here I am focused on what the PR is meant for.

**Comment by slubwama** [comment]
@ssmusoke 
1. About  Which platform they require. if you mean this `<openMRSVersion>1.11.6</openMRSVersion> `That defines the lowest OpenMRS platform which the module may depend on. Actually 1.11.x can work with Java 8. This was proven when we deployed it with platform 1.11.x
2. It does compile with both 7 & 8 also can run in both.
The platform thing should not confuse you.

**Comment by ssmusoke** [comment]
Indeed while it works now, I think we should target platform 2.x and Java 8 as the minimum so that as we upgrade other modules we do not run into issues, even as we may go to higher versions of the platform during the next cycle

**Comment by slubwama** [comment]
@ssmusoke whatever changes about changing platforms. They will not be handled in this PR.

**Comment by ssmusoke** [comment]
I have not said you add it to this PR - I am just saying it needs to be taken care of at some point - better now than later

**Comment by slubwama** [comment]
@ssmusoke  create the ticket for that

**Comment by slubwama** [comment]
Combined PR

**Pull request closed without merging**
