### PR TITLE
Enhance Search Functionality in Fingerprint Module

### PR DESCRIPTION
**Pull request by slubwama**
https://app.asana.com/0/1133167201254913/1139796124261011
Change Search to Load Patient In search List from redirect to patient dashboard

https://app.asana.com/0/1133167201254913/1139796124261012
Add Action on each of search return result

https://app.asana.com/0/1133167201254913/1139796124261013
Enable Checkin of patient after search of record

https://app.asana.com/0/1133167201254913/1139796124261014
Enable Printing of Registration ticket.

### CODE REVIEW

**Comment by slubwama** [comment]
@solemabrothers for your review

**Comment by solemabrothers** [comment]
@slubwama time functionality works fine

**Comment by solemabrothers** [comment]
> 
> 
> https://app.asana.com/0/1133167201254913/1139796124261011
> Change Search to Load Patient In search List from redirect to patient dashboard
> 
> https://app.asana.com/0/1133167201254913/1139796124261012
> Add Action on each of search return result
> 
> https://app.asana.com/0/1133167201254913/1139796124261013
> Enable Checkin of patient after search of record
> 
> https://app.asana.com/0/1133167201254913/1139796124261014
> Enable Printing of Registration ticket.

@slubwama  These are all functional, except i cant access the patient dashboard to add finger print

**Comment by solemabrothers** [comment]
@slubwama using the finger print doesnt return the patient name

**Pull request merged**
