### PR TITLE
Adding PersonAtttibuteType for  Finger Print

### PR DESCRIPTION
**Pull request by slubwama**

### CODE REVIEW

**Comment by ssmusoke** [comment]
@slubwama  see https://github.com/METS-Programme/openmrs-module-ugandaemr-fingerprint/pull/2/commits/5386a0ab61280a97cc63607fa2c4be0ecccfb61f

1. The groupId is always org.openmrs.module however the artifcatId is ugandaemrfingerprint - if you only use fingerprint it will cause issues in the Maven repors

2. The classes need to be in the package org.openmrs.module.ugandaemrfingerprint

**Comment by slubwama** [comment]
@ssmusoke  there are some dependencies that are picked from Digital Persona that can not be found in org.openmrs.module so some dependencies will have to remain like that. Nothing much to do about it.

But I am going to correct the ones of fingerprint to ugandaemrfingerprint

**Comment by slubwama** [comment]
@smuwanga  @ssmusoke on second thought This project may be shifted to be an openmrs project. Localizing it to be only a ugandaemr project may be short sightedness. Lets keep it that way

**Comment by carapai** [comment]
@slubwama 

What is the use of getResponseString function, do you plan to use it in feature?
Can you also remove System.out.println statements on Patient Search Widget Controller.

**Comment by carapai** [comment]
Generally there is need to re look at PatientSearchWidgetFragmentController, for example the password and username is hard coded, what happens if the use does not exist

**Pull request merged**
