### PR TITLE
Enhance search online by National ID from the patient search widget.

### PR DESCRIPTION
**Pull request by slubwama**
https://trello.com/c/NFRfGotw/746-fingerprint-eliminate-viewing-of-previously-searched-patients-on-the-search-page

https://trello.com/c/cAt3Zz9M/747-make-online-search-by-nin-be-done-at-the-patient-search-widget

#21

#22

Reference to Previous commits are in #23  Closed due to wrong branch of commit

### CODE REVIEW

**Comment by slubwama** [comment]
@ssmusoke Noticed that I had opened wrong branch.

**Comment by ssmusoke** [comment]
@slubwama error compiling the module 

`[ERROR] Failed to execute goal on project ugandaemrfingerprint-api: Could not resolve dependencies for project org.openmrs.module:ugandaemrfingerprint-api:jar:1.0.5-SNAPSHOT: The following artifacts could not be resolved: com.digitalpersona.fingerprint:fp-enrollment:jar:2.2.0, com.digitalpersona.fingerprint:fp-verification:jar:2.2.0, com.digitalpersona.onetouch:ot-api:jar:2.2.0, com.digitalpersona.onetouch:ot-jni:jar:2.2.0: Failure to find com.digitalpersona.fingerprint:fp-enrollment:jar:2.2.0 in http://mavenrepo.openmrs.org/nexus/content/repositories/public was cached in the local repository, resolution will not be reattempted until the update interval of openmrs-repo has elapsed or updates are forced -> [Help 1]
`

**Comment by slubwama** [comment]
@ssmusoke in the message i see cached. make sure that your .m2 is being updated

**Comment by ssmusoke** [comment]
@slubwama I got the same error when i deleted my `.m2/repository/com/digitalpersona` directory and running `mvn clean install -U` which updates all dependencies.

Where are the digital personal libraries obtained from - can you provide a url? This may need to be added to the repositories section of the main pom.xml

**Pull request merged**
